name: Daily UOS Notices
on:
  schedule:
    - cron: "00 18 * * *"   # UTC 18:00 = KST 03:00, 매일 1회
  workflow_dispatch: {}    
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run crawler
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_CHARSET: "utf8mb4"
        run: |
          python html_image_merge_crawler.py

      - name: Commit and push screenshots
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add screenshot/
          git commit -m "Update screenshots"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}